name: Test CI CD
on:
  push:
    branches: [tuong-dep-trai]
jobs:
  tuong-dep-trai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run tests
        run: npm run test
  
